FROM httpd:2.4
COPY ./htdocs/ /usr/local/apache2/htdocs/
EXPOSE 80
ADD LICENSE LICENSE
MAINTAINER mark.horwath@wtsintegration.com
LABEL Description="This image is used for the HTTP content portion of the WTS ADSI sample application, built from github (https://github.com/WTS-I/ADSI) tag DEV_${SOURCE_BUILD}"
